### ISSUE TITLE
Ca va?

### ISSUE THREAD

**Issue by backes-louis** [YorYvLou/Readme#1]
J'aimerais savoir si ça va Tom et Yves?
![kawaii-strawberry-chocolate-milk-cute-cartoon-box-best-friends-couple-two-cartons-drinking-straw-smiling-face-isolated-150661191](https://user-images.githubusercontent.com/61192956/74743773-4b7cd900-5261-11ea-9796-b78ad99d0394.jpg)

**Comment by backes-louis** [comment]
je suis pd !

**Comment by backes-louis** [comment]
Ok

**Comment by leonard-tom** [comment]
We should genuinely use this for something you know.
